Use base64 encoded file instead of multipart upload
veryfi/veryfi-go pull request #4
Opened 2021-08-19 19:15 UTC by hoanhan101

2021-08-24 13:55 UTC, manycoding requested changes
I don't see any tests in GitHub actions - do you have any? How do you test it?

2021-08-24 13:55 UTC, manycoding commented on veryfi/client.go
>  func (c *Client) ProcessDocumentUploadBase64(opts scheme.DocumentUploadBase64Options) (*scheme.Document, error) {
I think it doesn't make sense to keep this one. The feature is the same as ProcessDocumentUpload

2021-08-24 16:40 UTC, hoanhan101 commented
Tests can be performed locally. Github actions is not setup yet. I'll do that in other PR --> https://github.com/veryfi/veryfi-go/issues/5.

2021-08-30 15:32 UTC, manycoding commented
What about my comment?

2021-08-30 19:01 UTC, hoanhan101 commented
@manycoding Yes I think `ProcessDocumentUploadBase64` should be deleted as well. I'll make PRs for both of these changes today.

2021-08-31 16:14 UTC, manycoding approved these changes

2021-08-31 22:25 UTC, merged